version: v1
service:
  name: service1
  image: httpd:2.4.46 #oldservertest:1.0 #镜像
  deploy:
   mode: replicated # 指定 deploy 的模式	global:每个集群节点都只有一个容器;replicated:用户可以指定集群中容器的数量(默认) 
   replicas: 3 #副本数量
   timeout: 3 #超时时间
   agentTryNum: 3 #agent端操作失败后尝试次数
   placement: 
     constraints:
     - node.hostname == 192.168.43.166 #1.node.role == worker 2.node.hostname  3.node.labels.role == db
   resources:
   -  name: limits
      cpus: '0.50'
      memory: 50M
   -  name: requests
      cpus: '0.25'
      memory: 20M

